### ISSUE TITLE
WebGL2 returns null when accessing lime.graphics.RenderContext [Desktop, Windows]

### ISSUE THREAD

**Issue by kevansevans** [haxelime/lime#1387]
![Screenshot 2020-02-28 13 58 31](https://user-images.githubusercontent.com/10257965/75587373-8e923580-5a33-11ea-9eff-6843444c2daa.png)

Lime.software's Docs says this should be available, but upon running program it returns null. Tested for C++ and HashLink. C++ crashes with a null object reference, HL just shows a black screen.

Using Lime 7.7.0
```
import lime.app.Application;
import lime.graphics.RenderContext;
import lime.graphics.WebGL2RenderContext;
import lime.graphics.opengl.GLProgram;

class Main extends Application 
{

	public function new() 
	{
		super();
	}
	
	var gl:WebGL2RenderContext;
	var program:GLProgram;
	
	public override function render(context:RenderContext):Void 
	{
		switch (context.type) 
		{
			case OPENGL, OPENGLES, WEBGL:
				
				gl = context.webgl2; //context.webgl2 is null
				program = gl.createProgram(); //crashes here
				
				//none of this will obviously run
				gl.viewport(0, 0, window.width, window.height);
				gl.clearColor(1.0, 1.0, 1.0, 1.0);
				gl.clear(gl.COLOR_BUFFER_BIT);
				
			default:
		}
	}
	
}

```

[WebGL2RenderContext.zip](https://github.com/haxelime/lime/files/4269131/WebGL2RenderContext.zip)

**Comment by jgranick** [comment]
OpenGL ES 3.0 compatibility is required to support a WebGL 2 compatibility context.

This is disabled on current versions for macOS and Windows due to issues linking at compile-time:

https://github.com/haxelime/lime/blob/develop/project/src/graphics/opengl/OpenGL.h#L76

It is enabled for Linux and iOS. Either something may change in the underlying OS SDKs we use to define all symbols, or changes to SDL's OpenGL headers, or we move to a different system (with dynamic runtime linking) instead of the SDL GL approach. A dynamic system would be ideal (long-term) for supporting a broader variety of OpenGL desktop features beyond GLES3.
