### ISSUE TITLE
Cannot embed audio on cpp ("Cannot cache non-AudioBuffer asset")

### ISSUE THREAD

**Issue by zanzlanz** [haxelime/lime#1477]
### Version
Lime 7.9.0, Haxe  4.2.3, Windows 10.

### Problem
Audio assets, like `.OGG`, do not appear to properly embed on the cpp target.
Loading assets will work as expected with `embed="false"`, but not with `embed="true"`.

The error is thrown by `AssetCache`, though it looks like the message gets cut off before `" as AudioBuffer"`:
```
Cannot cache non-AudioBuffer asset: OggS
```

### Workaround
I'm not aware of any workarounds at this time, other than to simply not embed assets.

### Example Project
Small sample project for replicating included below, including a `test.ogg`. Run with `lime test cpp`.
[LimeSoundTest.zip](https://github.com/haxelime/lime/files/7240058/LimeSoundTest.zip)

### Code
```hx
package;

import lime.media.AudioSource;
import lime.utils.Assets;
import lime.app.Application;

class Main extends Application {
  override function onPreloadComplete():Void {
    try {
      Assets.loadAudioBuffer("assets/test.ogg").onError(function(e) {
        trace("Error: " + e);
      }).onComplete(function(buffer) {
        new AudioSource(buffer).play();
        trace("Success!"); // Traces when embed="false"
      });
    } catch(e) {
      trace("Uncaught error: " + e); // Traces when embed="true": "Uncaught error: Cannot cache non-AudioBuffer asset: OggS"
    }
  }
}
```

**Comment by zanzlanz** [comment]
When statically building Lime, the error returned in the console is simply: `Error: C` instead of the full error displayed in the title.

Is there a workaround using the `@:sound` metadata macro? I cannot find any explanation of how to use this in Lime.

**Comment by zanzlanz** [comment]
After comparing with OpenFL, it became clear the big difference was that I was using `loadAudioBuffer(...)` instead of `getAudioBuffer(...)`, an important detail which led to the above errors.

In the end it was a simple mistake, however the errors returned felt pretty misleading. Perhaps that could be cleaned up a bit?
For now I'll close the issue though. :)

**Comment by player-03** [comment]
Great sample code; it made tracking this down surprisingly easy. Makes me wish I'd taken a look at this sooner.

Turns out, `loadAudioBuffer` forgot to create a `AudioBuffer` object (which is the whole point; it's even in the function name). The error message was actually right - it really wasn't the right data type.

Also, the reason the error messages got cut off was, it tried to print out the full `Bytes` object, producing lots of invalid characters and messing up the output display.

**Comment by zanzlanz** [comment]
Hey thank you so much for taking a look at this and offering that fix! I'm so happy this was closed off properly.

I just confirmed your fix solves the issue for me without me needing a compiler branch. Perfect! 🎉

**Comment by player-03** [comment]
Oh wait, I remember why I didn't look at this sooner. From your description, it sounded like either an audio parsing error or an asset embedding error, and both of those things are magic as far as I'm concerned. (That is, they're outside my wheelhouse.)

It was only when you mentioned that you could fix it by changing "`loadAudioBuffer`" to "`getAudioBuffer`" that I realized it must be something simple. I even ended up copying the code from `getAudioBuffer` to fix the error. So yeah, I also need to give you credit for locating the solution.

You know, sometimes I spend hours or days debugging something, and it comes down to a single line of code. And I think to myself, "if only I'd been told to look at this line, I'd have finished debugging in a matter of minutes." Turns out, it's literally true! (The timestamps come out to about a half hour, but some of that was writing the commit message.)
