### ISSUE TITLE
[Android] Are symbol tables even possible without upgrading NDK version?

### ISSUE THREAD

**Issue by MercutioGraveman** [haxelime/lime#1490]
I'm running Lime with 

> android-ndk-r21e
> gradle 6.71
> gradle-plugin 4.2.0
> 

and gradle certainly understands the directive in gradle.build:

> 
> ndkVersion "21.4.7075529"
> 	
> buildTypes {
>   release {
>     minifyEnabled false
>     signingConfig signingConfigs.release
> 			
>     ndk {
>        debugSymbolLevel 'FULL'
>        }
>    }
>}

but it fails to produce either a symbols.zip file for an apk or 

>BUNDLE-METADATA\com.android.tools.build.debugsymbols\<ABI>\libX.dbg

in the an app bundle.  

I tried the next ndk after that (r22b) but Lime doesn't compile with it.  My concern now is that at it's current highest ndk, Lime won't be able to debug stack traces from Google Play.  Is this correct?

**Comment by player-03** [comment]
I'd say give [.hxcpp_config.xml](https://github.com/HaxeFoundation/hxcpp/blob/master/toolchain/example.hxcpp_config.xml) a shot. Look for it in your home directory.

There are other xml files lying around that you could modify, but you really shouldn't have to.

**Comment by MercutioGraveman** [comment]
Thanks, p3.  Google Play wasn't able to utilize the uploaded symbols.zip automatically, but I was able to use _ndk-stack_ along with those libs to locally parse their stack dumps.  

This whole business certainly hasn't been obvious to me.  If I can get access to publish on the OpenFL website, I'll document what I've learned of OpenFL's Android build process.  It should all be in one place, especially now that app bundles are required.

**Comment by player-03** [comment]
> Google Play wasn't able to utilize the uploaded symbols.zip automatically

Any idea why not? Google Play uses `ndk-stack` too; if it works locally, it should work on their servers.

Though now that I think about it, I recall a warning that it doesn't work retroactively. Try checking your latest crash reports, from after uploading symbols.zip.

> If I can get access to publish on the OpenFl website, I'll document what I've learned of OpenFl's Android build process. It should all be in one place, especially now that app bundles are required.

This is more of a Lime issue, so it'd fit better [on lime.software](https://lime.software/docs/advanced-setup/android/).

**Comment by MercutioGraveman** [comment]
I uploaded a fresh build to test.  It seemed to me that uploading symbols.zip is an apk artifact.  Bundles expect to have their symbols included in the BUNDLE-METADATA directory within the bundle itself.

**Comment by player-03** [comment]
When I upload a bundle, I can still upload symbols afterwards, and it all works.

**Comment by MercutioGraveman** [comment]
At any rate, the issue was generating symbol tables and even with local symbols, I am able to debug.  Thanks again.

**Comment by tobil4sk** [comment]
I was interested in this recently, as it's useful to have readable crash logs from google play, even if they don't map directly to the haxe source lines.

> Bundles expect to have their symbols included in the BUNDLE-METADATA directory within the bundle itself.

It seems like there is now a fairly convenient process with publishing .aab files and having the symbols handled/added automatically by gradle and the packaging process.

1. Firstly, as already mentioned you need to add `-D HXCPP_DEBUG_LINK` to your app build. This gives you binaries with debug symbols for your app code.
2. Gradle already automatically strips out the symbols, so tell it to include them in the .aab's `BUNDLE-METADATA`. See documentation: https://developer.android.com/build/include-native-symbols#agp-4.1. Currently you have to copy `templates/android/template/app/build.gradle` and add:
```groovy
android {
	buildTypes {
		release {
			// ...
			ndk {
			 	debugSymbolLevel 'FULL' // or 'SYMBOL_TABLE'
			}
		}
	}
}
```
3. Build an .aab file using lime and double check that debug symbols have been included in the `BUNDLE-METADATA`.

This process is nice as you still get stripped binaries deployed to users, so the app size is smaller, but gradle automatically adds the symbols to the aab and they get uploaded as part of your .aab file. Maybe step 2 could be made simpler, as most app developers would probably find it useful to have this as an option.

One thing to note is that you won't have symbols for `liblime.so`, since that doesn't include debug symbols in the haxelib release (they would increase the installation size). If you want this you can do `lime rebuild android -DHXCPP_DEBUG_LINK`.

--- 

One issue I ran into with a modern gradle setup is that you need to have an ndkVersion in your build.gradle (lime does this since: 2e578d3e569dd369bba8d86933486485f62948c6). Before this patch if ndkVersion is not set, gradle sets its own internal ndkVersion, and if that doesn't match the version at ndkPath then you get errors like this:
```
> Task :app:stripReleaseDebugSymbols
[CXX1100] android.ndkVersion is [26.3.11579264] but android.ndkPath /usr/local/lib/android/sdk/ndk/27.3.13750724 refers to a different version [27.3.13750724].
[CXX1100] android.ndkVersion is [26.3.11579264] but android.ndkPath /usr/local/lib/android/sdk/ndk/27.3.13750724 refers to a different version [27.3.13750724].
Unable to strip the following libraries, packaging them as they are: libApplicationMain.so, liblime.so.

> Task :app:buildReleasePreBundle

> Task :app:extractReleaseNativeDebugMetadata
[CXX1100] android.ndkVersion is [26.3.11579264] but android.ndkPath /usr/local/lib/android/sdk/ndk/27.3.13750724 refers to a different version [27.3.13750724].
```
This means the binaries have not been stripped, so the binary size is large and you won't see symbols in the crash log. Solution is to update to modern lime and update any manually maintained gradle templates.
